### PR TITLE
fix: run all verification checks before exiting

### PR DESCRIPTION
**Pull request by Jaryt**

### CODE REVIEW

**Comment by KyleTryon** [comment]
Weird new shellcheck error unrelated to this. could you add this to the offending line?

`# shellcheck ignore=SC21531

**Review by KyleTryon — APPROVED** [review]
Good change 👍

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:daa8d4b88ff3e4dd7cc9b603f95b934a1c7d8dd1

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:00399c42b6c9de108cedf1100aeca0b9a46f1a65

**Pull request merged**
