### PR TITLE
trigger-integration-workflow: make cleanup-tags use tag parameter

### LINKED ISSUE #41: trigger-integration-workflow's cleanup-tags option only cleans up hardcoded tags
### Orb version
v1.27.1

### What happened
When running `trigger-integration-workflow` with `cleanup-tags: true` and with a non-default `tag` param  (i.e., `tag: custom_tag`), my previous `custom_tag-*` tags don't get cleaned up.

### Expected behavior
I expect my previous tags that match my `tag` param to be deleted.

### Other comments
I noticed this in the `trigger-integration-workflow` [source](https://github.com/jrnail23/orb-tools-orb/blob/master/src/jobs/trigger-integration-workflow.yml#L131):
```sh
# delete local tags
git tag -d $(git tag -l "integration-*")
git tag -d $(git tag -l "master-skip-master-*")
# fetch remote tags
git fetch
# delete remote tags
git push origin --delete $(git tag -l "integration-*") || true
git push origin --delete $(git tag -l "master-skip-master-*") || true # pushing once should be faster than multiple timesshould be faster than multiple times
```

and it seems that
```sh
$(git tag -l "integration-*")
```
should probably be changed to
```sh
$(git tag -l "<<parameters.tag>>-*")
```

However, I'm not sure what to do about `$(git tag -l "master-skip-master-*")` though.

### PR DESCRIPTION
**Pull request by jrnail23**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues
resolves #41 

### Description
Change `trigger-integration-workflow` to make its `cleanup-tags` option delete previous tags matching the `tag` parameter.

### CODE REVIEW

**Comment by iynere** [comment]
hmmmmm, actually, with this PR, the second line (`git tag -d $(git tag -l "master-skip-master-*"`) isn't even necessary, as it will already be hit by the first wildcard..... maybe this isn't such an ideal fix. because sometimes folks don't want to delete those `master` tags at all....

let me try to take a look at refactoring some of this logic in a more holistic way, unless you have any other ideas @jrnail23 

if there are specific tags you want to delete in the interim, i'd recommend doing so as a `post-step`—should be easy, since all the `giit config` commands will already have been run for you.

**Comment by jrnail23** [comment]
@iynere, the only way `"master-skip-master-*"` would get hit is if you specified `tag: master`, right?

**Comment by iynere** [comment]
what i'm saying is that, `git tag -d $(git tag -l "<<parameters.tag>>-*"` will _already_ delete any tags that `git tag -d $(git tag -l "master-skip-master-*"` would delete @jrnail23 so the second command is redundant......

and the purpose of structuring it the original way, was specifically to avoid deleting tags like `master-minor-etc` or `master-major-etc`, which, with this PR, would be deleted

**Comment by jrnail23** [comment]
If you set up your job like this:
```yaml
- orb-tools/trigger-integration-workflow:
    cleanup-tags: true
    tag: testing
```

that git command would end up looking like this:
```sh
# delete local tags
git tag -d $(git tag -l "testing-*")
git tag -d $(git tag -l "master-skip-master-*")
# fetch remote tags
git fetch
# delete remote tags
git push origin --delete $(git tag -l "testing-*") || true
git push origin --delete $(git tag -l "master-skip-master-*") || true
```
That would only delete tags named `testing-*` or `master-skip-master-*`

**Comment by iynere** [comment]
i'm talking about the edge case where `tag` = `master @jrnail23 

which is the important one to look out for, since those tags have the possibility of being linked to a production orb release, in which case we wouldn't want to delete them

**Comment by jrnail23** [comment]
@iynere, I understand your concern about deleting `master-` tags unintentionally, but the other side of the coin here is that since I'm using `tag: rc` for this job on my `master` branch, I've got five tags named `rc-patch-master-MY_SHA7` after only a day of development.

Your suggestion to run a `post-step` is very helpful, but I don't really want to put that in all five of the orbs I'm maintaining.
I'll experiment a bit here, and let you know what I learn from it.

**Comment by jrnail23** [comment]
@iynere: so it looks like `post-steps` aren't an effective substitute here. The actual `cleanup-tags` happens _before_ the new integration tag is applied.  Running it in `post-steps` actually deletes the newly created `INTEGRATION_TAG` immediately upon creation.

Running it in `pre-steps` would seem preferable, but in that case, it's happening before the checkout, or any of the `git config` stuff is run by the job, so makes it a lot less workable.

I keep circling back to the idea of `cleanup-tags` already being an opt-in thing, but I understand that you wouldn't want to surprise anyone with breaking behavior, even if it fixes an existing bug.  

Myself, I'm generally using your prescribed workflow (modified to use manual approvals to release patch/minor/major instead of the SemVer inference behavior), and using the default `publish-version-tag` behavior on `dev-promote-prod`, so I don't really care too much about keeping tags for integration test versions, particularly since the orbs are getting saved as artifacts in the `lint-pack_validate_publish-dev` workflow.

Anyway, I hope that helps you come up with an acceptable solution to cleaning up the cruft from test runs.

**Comment by iynere** [comment]
hmmm, let's just merge it—since orb-tools now creates different production release tags anyway @jrnail23 

& this will all change / improve very soon anyway—once this is done https://github.com/CircleCI-Public/api-preview-docs/blob/master/designs-for-feedback/trigger-workflows-in-pipeline.md git tags will mostly go away here completely 🎉

**Comment by jrnail23** [comment]
@iynere Excellent.  And I'm looking forward to seeing what you come up with for the workflow triggering feature.

**Pull request merged**
