### PR TITLE
feat(scripts): add pretty output to review job

### PR DESCRIPTION
**Pull request by wyardley**
Use pretty output to stdout / stderr, and then also save the junit report

The test results will still be included in the "tests" tab, but this should make the test output a little easier to follow.

note: I'm happy to add back the additional messages and exit code / pointer to look at the tests, but I think this may work as expected without it?

### CODE REVIEW

**Comment by wyardley** [comment]
@KyleTryon rebased and fixed the shellcheck warning

**Comment by orb-publisher** [comment]
Your development orb(s) have been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link(s): 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:845949f5a119ea93ec72ee854faa25fc0b981b96
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:alpha

**Comment by KyleTryon** [comment]
jk it went through 🎉

**Comment by wyardley** [comment]
image

tested it on one of our projects that uses this with the tag, and that works Ok.

**Review by KyleTryon — APPROVED** [review]
I agree, with the output flag there shouldn't be a need to "hack" the exit code. Great addition!

**Comment by wyardley** [comment]
image
and tests still show up too, despite the filename changing slightly (but not the directory)

**Comment by orb-publisher** [comment]
Your development orb(s) have been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link(s): 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:1d2ddd8fbcda6e84436dc71d49297dc7f2220ee4
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:alpha

**Comment by KyleTryon** [comment]
Thank you @wyardley

**Comment by KyleTryon** [comment]
Though this was technically a feat, I broke the rules to include it as a patch.
image

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=12.0.2

**Pull request merged**
