### PR TITLE
fix(scripts): include name and commit hash when publishing

### LINKED ISSUE #204: Dev orb publishing comment missing
## Orb version:
12.0.0

## What happened:
```
Your development orb(s) have been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link:
[https://circleci.com/developer/orbs/orb/?version=dev:dev:${CIRCLE_SHA1}](https://circleci.com/developer/orbs/orb/?version=dev:dev:$%7BCIRCLE_SHA1%7D)
```
## Expected behavior:
The comment should include the orb name and the expanded commit hash

## Additional Information:

### PR DESCRIPTION
**Pull request by wyardley**
- Use `ORB_PARAM_ORB_NAME` vs `ORB_VAL_ORB_NAME`
- Fix literal expansion of `CIRCLE_SHA1`

Fixes #204

### CODE REVIEW

**Comment by wyardley** [comment]
Note: haven't fixed the SHA1 bit yet - was seeing if I would get a test version published when I submitted this.

**Comment by KyleTryon** [comment]
Thank you @wyardley. Actually, you showed me we forgot a crucial step. in fact, everything that says param should say val, according to our internal style guides. I am going to quickly go in and fix actually all of the other names instead.

**Comment by KyleTryon** [comment]
I believe i see the comment issue as well

**Comment by wyardley** [comment]
Ok, sounds good! I'll close this then.

**Pull request closed without merging**
