### PR TITLE
feat: custom publishing tag pattern

### LINKED ISSUE #172: Allow to release a development version of an orb with a custom tag
## Describe Request:
In the old orb tools version, it was possible to create a development release of an orb with a custom version tag, e.g. `dev:<branch-name>`. This allowed for easy testing of changes in an orb without having to bump the orb version after every commit to an orb, AND to have a master branch which always published the `dev:alpha` version.

With the current Orb version, this is a bit more troublesome. There are now 2 tags created: 
- `dev:alpha`
- `dev:<SHA1>`

We could use the `dev:alpha` tag when working on a branch, however it might be overridden by pipeline run by another branch. And we would also loose the possibility to use the `dev:alpha` tag to always get the latest (not released) orb version. 

I see 2 possible solutions to achieve what I would like:
1. Depending on the branch that the publish job is run from, create a different tag. For master, use `dev:<SHA-1>`, for other branches, use `dev:<branch_name` (taken from the `CIRCLE_BRANCH` env var. This is however a bit opinionated, and potentially not backwards compatible.
2. Allow to specify the additional tag. through a new property e.g. `pub-dev-tag` By default, the `dev:<SHA-1>` tag could be used, which preserves backwards compatibility. With the new property, a custom tag can then be specified for versions published from a branch.

## Supporting Documentation Links:
The documentation still refers to branch versions for a development orb: https://circleci.com/docs/orb-concepts/#development-orbs

### PR DESCRIPTION
**Pull request by KyleTryon**
Aims to resolve #172

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:6750ada7cc2e60169b50525860fadf1c829a5b17

**Review by EricRibeiro — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:fbf8a7ea63438842dea8f5b5240bd28d15548a8f

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=dev:fbf8a7ea63438842dea8f5b5240bd28d15548a8f

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=11.6.0

**Pull request merged**
