### PR TITLE
chore(examples): remove extra `-` for steps

### PR DESCRIPTION
**Pull request by clementlecorre**
## Description:

Fix example steps

## Motivation:

bad syntax 

**Closes Issues:**

- ISSUE URL

### CODE REVIEW

**Review by Tiagoqt — APPROVED** [review]
HVK

**Review by Tiagoqt — APPROVED** [review]
xfvx

**Review by Tiagoqt — APPROVED** [review]

**Review by Tiagoqt — APPROVED** [review]

**Review by Tiagoqt — APPROVED** [review]
ok

**Review by KyleTryon — APPROVED** [review]

**Comment by KyleTryon** [comment]
Much appreciated  @Tiagoqt

**Pull request merged**
