### PR TITLE
fix: Allows to use any string as tag for trigger-integration-workflow

### PR DESCRIPTION
**Pull request by KillianHmyd**
### Checklist

- [X] All new jobs, commands, executors, parameters have descriptions
- [X] Examples have been added for any significant new features
- [X] README has been updated, if necessary

### Motivation, issues

In my use case I have a mono-repository for all my orbs. I need to be able to specify the tag used during the job `trigger-integration-workflow` to be able to trigger different deployment according to which orbs have been changed.

### Description

- modify `tag` parameter to job `trigger-integration-workflow` from `enum` to `string`

### CODE REVIEW

**Comment by iynere** [comment]
@KillianHmyd makes sense!

just out of curiosity, is something like this not already a possibility for u ?

https://github.com/CircleCI-Public/circleci-orbs/blob/master/.circleci/config.yml#L126-L148

**Comment by KillianHmyd** [comment]
@iynere Yes it could definitely be a possibility but I'll need to also add the `pack` before promoting and do the same logic to trigger the prod release

**Comment by iynere** [comment]
i guess i'm asking because this orb is designed for a very particular purpose—doing orb integration testing—and what you're wanting to use it for is essentially just to trigger git tags to do monorepo stuff. the 2 are _related_ but not identical usecases—& probably what would be better, would be a dedicated monorepo orb (which is something we have been talking about internally). what do you think?

**Comment by KillianHmyd** [comment]
@iynere Oh, I misunderstood the main purpose of this orb.
Indeed having an orb dedicated to the CIs of mono-repo orbs would be very useful.

Knowing that I don't know if this PR still makes sense

**Comment by iynere** [comment]
@KillianHmyd i can go ahead and merge this, as it doesn't actually alter our usage of the command at all, but i just wanted you to know the full context. i will modify your code a bit first though

**Pull request merged**
